server:
  port: 8082
  servlet:
    context-path: /community
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nowcoder?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: Donnyjin1
  application:
    name: community
  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html
    mode: HTML5
    prefix: classpath:/templates/
  #MailProperties
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465
    username: 1171314644@qq.com
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    password: mttbyzbjoiclfgef

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  type-aliases-package: com.donny.community.entity

#community
community:
  path:
    domain: http://localhost:8082
    context-path: /community
    upload: D:\idea_project\WorkerCommunity\upload


#logging:
#  level:
#    com.donny.community = debug
